#!/bin/bash

# 現在のチャンネルを取得する
channel=$(iwconfig | grep "Channel" | awk '{print $2}')

# 空いているチャンネルを検索する
channels=$(iwlist scan | grep -E "Channel: |Frequency:" | awk '{print $2}')

# 空いているチャンネルがある場合は、変更する
if [ -n "$channels" ]; then
    for channel in $channels; do
        if [ "$channel" != "$current_channel" ]; then
            iwconfig wlan0 channel $channel
            break
        fi
    done
fi
